version: "3.8"

networks:
  server:
  client:

services:
  # server:
  #   container_name: linkumg_server
  #   build:
  #     context: server
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./server:/app
  #   stdin_open: true
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - server
      
  front:
    command: "yarn start"
    container_name: linkumg_client
    build:
      context: "./client"
      dockerfile: Dockerfile.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - ./client:/home/node/ui
      - /home/node/ui/node_modules
    # depends_on:
    #   - server

